algoritmo "OPERADORES LÓGICOS E RELACIONAIS"
var
A, B, C: Inteiro
inicio
   A <- 2
   B <- 3
   C <- 5
   //Operadores relacionais
   Escreval(A>B)
   Escreval(A=B)
   Escreval(A<>B)
   Escreval(A>=B)
   Escreval(A<=B)
   Escreval(C=A+B)
   Escreval(C>=B^A)
   Escreval(C<=B^A)
   Escreval(B<=C%2)
   Escreval(1=C%2)
   //Operadores lógicos
   Escreval(verdadeiro e falso)
   Escreval((A=B)ou(C>A))
   Escreval(nao((A=B)ou(C>A)))         //Inverte o resultado logico

fimalgoritmo